### ISSUE TITLE
gulp 命令出错

### ISSUE THREAD

**Issue by nasawz** [YangQiGitHub/wx-miniprogram-boilerplate#2]
`TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

**Comment by nasawz** [comment]
应该是gulp问题

**Comment by sandmanman** [comment]
请问如何解决的？
